export const ACCOUNTS = [
    { code: 'AC-CA', name: 'Caja', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'AC-BA', name: 'Bancos', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'AC-IN', name: 'Inventarios', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'AC-CL', name: 'Clientes', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'AC-IV', name: 'IVA Acreditable', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'AC-IP', name: 'IVA por Acreditar', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'ANC-ME', name: 'Mobiliario y Equipo', type: 'Activo No Circulante', nature: 'Deudora' },
    { code: 'ANC-EC', name: 'Equipo de Cómputo', type: 'Activo No Circulante', nature: 'Deudora' },
    { code: 'ANC-DAM', name: 'Depre. Acum. Mob.', type: 'Activo No Circulante', nature: 'Acreedora' },
    { code: 'ANC-DAC', name: 'Depre. Acum. Comp.', type: 'Activo No Circulante', nature: 'Acreedora' },
    { code: 'AD-GI', name: 'Gastos de Instalación', type: 'Otros Activos', nature: 'Deudora' },
    { code: 'AD-PU', name: 'Papelería y Útiles', type: 'Otros Activos', nature: 'Deudora' },
    { code: 'AD-RA', name: 'Rentas Pagadas Anticipado', type: 'Otros Activos', nature: 'Deudora' },
    { code: 'AC-FF', name: 'Fondo Fijo Caja Chica', type: 'Activo Circulante', nature: 'Deudora' },
    { code: 'PC-PR', name: 'Proveedores', type: 'Pasivo Corto Plazo', nature: 'Acreedora' },
    { code: 'PC-IT', name: 'IVA Trasladado', type: 'Pasivo Corto Plazo', nature: 'Acreedora' },
    { code: 'PC-IX', name: 'IVA por Trasladar', type: 'Pasivo Corto Plazo', nature: 'Acreedora' },
    { code: 'PC-AC', name: 'Anticipo Clientes', type: 'Pasivo Corto Plazo', nature: 'Acreedora' },
    { code: 'C-CS', name: 'Capital Social', type: 'Capital Contable', nature: 'Acreedora' },
    { code: 'C-UN', name: 'Utilidad Neta', type: 'Capital Contable', nature: 'Acreedora' },
    { code: 'C-PE', name: 'Pérdida Ejercicio', type: 'Capital Contable', nature: 'Deudora' },
    { code: 'RI-VE', name: 'Ventas', type: 'Resultados (Ingresos)', nature: 'Acreedora' },
    { code: 'RI-DC', name: 'Dev sobre Compra', type: 'Resultados (Ingresos)', nature: 'Acreedora' },
    { code: 'RI-RC', name: 'Reb sobre Compra', type: 'Resultados (Ingresos)', nature: 'Acreedora' },
    { code: 'RE-CO', name: 'Compras', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-GC', name: 'Gastos sobre Compra', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-DV', name: 'Dev sobre Venta', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-RV', name: 'Reb sobre Venta', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-GV', name: 'Gastos de Venta', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-GA', name: 'Gastos de Administración', type: 'Resultados (Egresos)', nature: 'Deudora' },
    { code: 'RE-GG', name: 'Gastos Generales', type: 'Resultados (Egresos)', nature: 'Deudora' },
];
